import random

randomSeed = '0.166241939035787'
random = random.Random(randomSeed)

# NETWORK SETTINGS
NUM_INIT_NODES = 600
NUM_SEEDERS = 6
NUM_NODES = 1000

# NODE TIME SETTINGS
RESTART_TIMEFRAME = 36000
RESTART_PERCENTAGE = .25
MEAN_START_TIME = 10000

# NODE TYPES
PEER = 0
SEEDER = 1
DARK = 2

# SEEDER ATTRIBUTES
DNS_QUERY_SIZE = 40 # actually 4000
TIME_BETWEEN_CRAWLS = 100

# NODE ATTRIBUTES
NUM_TRIED_BUCKETS = 64
NUM_NEW_BUCKETS = 256
ADDRESSES_PER_BUCKET = 64
MAX_INCOMING = 117
MAX_OUTGOING = 8
MAX_RETRIES = 3

# EVENT TYPES
RESTART = 0
DROP = 1
JOIN = 2
CONNECT = 3
CONNECTION_FAILURE = 4
REQUEST_CONNECTION_INFO = 5
CONNECTION_INFO = 6
REJOIN = 7

# LATENCY TYPES
UNIFORM = 0

# TODO Add more latency types.

# TERMINATION CONDITIONS
TERMINATION_COND_TIME = 0
TERMINATION_COND_NUM_NODES = 1
TERMINATION_COND_DIAMETER = 2
TERMINATION_COND_LCC_DIAMETER = 3
