import random

randomSeed = 166241939
random = random.Random(randomSeed)

# NETWORK SETTINGS
NUM_INIT_NODES = 400
NUM_SEEDERS = 6
NUM_NODES = 1000

# NODE TIME SETTINGS
RESTART_TIMEFRAME = 36000
RESTART_PERCENTAGE = .25
MEAN_START_TIME = 10000
W_LAMBDA = 73.3
W_K = 0.624

# RELEVANT TIME LENGTHS, IN SECONDS
ONE_DAY = 24 * 60 * 60
THIRTY_DAYS = 30 * ONE_DAY
WAIT_TIME_TO_CONCLUDE_REQUEST_LOST = 5

# NODE TYPES
PEER = 0
SEEDER = 1
DARK = 2

# SEEDER ATTRIBUTES
DNS_QUERY_SIZE = 40 # actually 4000
TIME_BETWEEN_CRAWLS = 100
SEEDER_REPLY_FAIL_RATE = 0.001

# NODE ATTRIBUTES
NUM_TRIED_BUCKETS = 64
NUM_NEW_BUCKETS = 256
ADDRESSES_PER_BUCKET = 64
MAX_INCOMING = 117
MAX_OUTGOING = 8
MAX_RETRIES = 3

# EVENT TYPES
RESTART = 0
DROP = 1
JOIN = 2
CONNECT = 3
CONNECTION_FAILURE = 4
REQUEST_CONNECTION_INFO = 5
CONNECTION_INFO = 6
REJOIN = 7
NEW_DAY = 8
USE_HARDCODED_IPS = 9
AFTER_REJOIN_MAYBE_REQUEST_SEEDER = 10
CONNECTION_INFO_ADDR = 11

reversedEventTypes = {
  RESTART: 'RESTART',
  DROP: 'DROP',
  JOIN: 'JOIN',
  CONNECT: 'CONNECT',
  CONNECTION_FAILURE: 'CONNECTION_FAILURE',
  REQUEST_CONNECTION_INFO: 'REQUEST_CONNECTION_INFO',
  CONNECTION_INFO: 'CONNECTION_INFO',
  REJOIN: 'REJOIN',
  NEW_DAY: 'NEW_DAY',
  USE_HARDCODED_IPS: 'USE_HARDCODED_IPS',
  AFTER_REJOIN_MAYBE_REQUEST_SEEDER: 'AFTER_REJOIN_MAYBE_REQUEST_SEEDER',
  CONNECTION_INFO_ADDR: 'CONNECTION_INFO_ADDR'
}

# MESSAGE TYPES
DNS_MSG = 0
ADDR_MSG = 1

# MESSAGE SETTINGS
MAX_ADDRS_PER_MSG = 1000
MAX_ADDRS_TO_FORWARD = 10
ADDR_LOWER_BOUND_PERCENT = 0.23
ADDR_UPPER_BOUND_NUM = 2500

# LATENCY TYPES
UNIFORM = 0

# TODO Add more latency types.

# TERMINATION CONDITIONS
TERMINATION_COND_TIME = 0
TERMINATION_COND_NUM_NODES = 1
TERMINATION_COND_DIAMETER = 2
TERMINATION_COND_LCC_DIAMETER = 3

# GRAPH SAMPLING MODES

GRAPH_SAMPLE_ALL = 0
GRAPH_SAMPLE_RND = 1
GRAPH_SAMPLE_LCC = 2

GRAPH_SAMPLE_RND_RATIO = 0.1

METRIC_EVENT_INTERVAL = 50

# MISC
HARDCODED_IP_SOURCE = '0.0.0.0'
